Universe = vanilla

Output = jobs/fit_output.$(Cluster).$(Process).out
Error = jobs/fit_output.$(Cluster).$(Process).err
Log = jobs/fit_output.$(Cluster).$(Process).log

Executable = ./trex_fit_wrapper.sh

request_memory = 8GB
request_cpus = 4


queue 1 arguments in (
    200, 225, 250, 275, 300, 325, 350, 375, 400, 425, 450, 475, 500,
    525, 550, 600, 700, 800, 900, 1000, 1500, 2000, 3000
)
+queue="short"
